server:
  port: 8761

spring:
  application:
    name: discoveryService

eureka:
  server:
    eviction-interval-timer-in-ms: 5000
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false